services:
  db:
    image: postgres:16-alpine
    container_name: erppos-db
    environment:
      POSTGRES_DB: erppos
      POSTGRES_USER: erpuser
      POSTGRES_PASSWORD: erppass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    profiles: ["dev"]
    container_name: erppos-backend
    environment:
      DATABASE_URL: postgresql+psycopg2://erpuser:erppass@db:5432/erppos
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    profiles: ["dev"]
    container_name: erppos-frontend
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:


