version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: erppos
      POSTGRES_USER: erpuser
      POSTGRES_PASSWORD: erppass
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://erpuser:erppass@db:5432/erppos
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:





