[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["app/tests"]
addopts = "-q"

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [
  "alembic/*",
]

[tool.ruff.lint]
select = ["E", "F", "I"]





